blog/accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("login/", views.login, name="login"),
    path("register/", views.register, name="register"),
    path("logout/", views.logout, name="logout"),
    path("dashboard/", views.dashboard, name="dashboard"),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("blog_app.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("accounts/", include("accounts.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blog_app/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path("", views.ArticleList.as_view(), name="home"),
    path("new/", views.ArticleNewView.as_view(), name="new_article"),
    path(
        "delete/<slug:slug>", views.ArticleDeleteView.as_view(), name="delete_article"
    ),
    path("articles/<slug:slug>/", views.ArticleDetail.as_view(), name="article_detail"),
]

blog/accounts/models.py
from django.db import models

# Create your models here.

blog/blog_app/models.py
from django.db import models
from django.contrib.auth.models import User


class Article(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_articles"
    )
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title

blog/blog_app/forms.py
from django import forms
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget

from .models import Article


class BasicArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        exclude = ("author", "is_read_only", "slug")
        widgets = {
            "content": SummernoteInplaceWidget(),
        }

blog/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib import auth

from blog_app.models import Article


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        password = request.POST["password"]
        password2 = request.POST["password2"]

        # Check if passwords match
        if password == password2:
            # Check username
            if User.objects.filter(username=username).exists():
                messages.error(request, "That username is taken")
                return redirect("register")
            else:
                if User.objects.filter(email=email).exists():
                    messages.error(request, "That email is being used")
                    return redirect("register")
                else:
                    user = User.objects.create_user(
                        username=username, password=password, email=email
                    )
                    user.save()
                    messages.success(request, "You are now registered and can log in")
                    return redirect("login")
        else:
            messages.error(request, "Passwords do not match")
            return redirect("register")
    else:
        return render(request, "accounts/register.html")


def login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user)
            return redirect("dashboard")
        else:
            messages.error(request, "Invalid credentials")
            return redirect("login")
    else:
        return render(request, "accounts/login.html")


def logout(request):
    auth.logout(request)
    return redirect("home")


def dashboard(request):
    user_articles = Article.objects.filter(author=request.user.id).order_by(
        "-created_on"
    )

    context = {"articles": user_articles}
    return render(request, "accounts/dashboard.html", context)

blog/blog_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.utils.text import slugify
from django.views import generic
from django.views.generic import FormView, DeleteView

from .models import Article
from .forms import BasicArticleForm


class ArticleList(generic.ListView):
    queryset = Article.objects.order_by("-created_on")
    template_name = "index.html"
    paginate_by = 3


class ArticleDetail(generic.DetailView):
    model = Article
    template_name = "article_detail.html"


class ArticleNewView(LoginRequiredMixin, FormView):
    form_class = BasicArticleForm
    template_name = "new_article.html"
    success_url = "/accounts/dashboard"

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.slug = slugify(obj.title)
        obj.save()

        return HttpResponseRedirect(self.get_success_url())


class ArticleDeleteView(LoginRequiredMixin, DeleteView):
    model = Article
    context_object_name = "article"
    success_url = "/accounts/dashboard/"
    template_name = "article_confirm_delete.html"

blog/templates/accounts/dashboard.html
{% extends 'base.html' %}
{% block content %}
<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <h1 class="display-4">{{ user.username|title }} Dashboard</h1>
                <p class="lead">Manage your BT Real Estate account</p>
            </div>
        </div>
    </div>
</section>

<section id="dashboard" class="py-4">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h2>Welcome {{ user.username|title }}</h2>
                {% if articles %}
                <p><a class="btn btn-dark" href="{% url 'new_article' %}">Create new article</a></p>
                <table class="table">
                    <thead>
                        <tr>
                            <th scope="col">Title</th>
                            <th scope="col">Created on</th>
                            <th scope="col">Last modified</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for article in articles %}
                        <tr>
                            <td>{{ article.title }}</td>
                            <td><p class=" text-muted">{{ article.created_on }}</p></td>
                            <td><p class=" text-muted">{{ article.updated_on }}</p></td>
                            <td><a class="btn btn-dark" href="{% url 'article_detail' article.slug %}">View</a></td>
                            <td><a class="btn btn-light" href="{% url 'delete_article' article.slug %}">Delete</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

                {% else %}
                <p><strong>You don't have any articles....</strong></p>
                <a class="btn btn-dark" href="{% url 'new_article' %}">Create new article</a>
                {% endif %}
            </div>
        </div>
    </div>
</section>
{% endblock content %}

blog/templates/accounts/login.html
{% extends 'base.html' %}
{% block title %}| Login{% endblock title %}
{% block content %}
<section id="login" class="bg-light py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="card">
                    <div class="card-header bg-primary text-white">
                        <h4>
                            <i class="fas fa-sign-in-alt"></i> Login</h4>
                    </div>
                    <div class="card-body">
                        <!-- Alerts -->
                        {% include 'partials/_alerts.html' %}
                        <form action="{% url 'login' %}" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="username">Username</label>
                                <input type="text" name="username" class="form-control" required>
                            </div>

                            <div class="form-group">
                                <label for="password2">Password</label>
                                <input type="password" name="password" class="form-control" required>
                            </div>

                            <input type="submit" value="Login" class="btn btn-secondary btn-block">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

blog/templates/accounts/register.html
{% extends 'base.html' %}
{% block content %}
<section id="register" class="bg-light py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-6 mx-auto">
                <div class="card">
                    <div class="card-header bg-primary text-white">
                        <h4>
                            <i class="fas fa-user-plus"></i> Register
                        </h4>
                    </div>
                    <div class="card-body">
                        <!-- Alerts -->
                        {% include 'partials/_alerts.html' %}
                        <form action="{% url 'register' %}" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <label for="username">Username</label>
                                <input type="text" name="username" class="form-control" required>
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" name="email" class="form-control" required>
                            </div>
                            <div class="form-group">
                                <label for="password2">Password</label>
                                <input type="password" name="password" class="form-control" required>
                            </div>
                            <div class="form-group">
                                <label for="password">Confirm Password</label>
                                <input type="password" name="password2" class="form-control" required>
                            </div>
                            <input type="submit" value="Register" class="btn btn-secondary btn-block">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

blog/templates/article_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="container-fluid">
    <div class="row ml-1 mr-1">
      <div class="col-md-12">
        <div class="card card-default mb-5">
          <div class="card-body">
              <section>
              <h4>Delete this article?</h4>
              <form method="post">{% csrf_token %}
                  <p>Are you sure you want to delete "{{ object }}"?</p>
                  <input class="btn btn-danger" type="submit" value="Confirm">
              </form>
            </section>
          </div>
        </div>
      </div>

    </div>
  </div>
{% endblock %}

blog/templates/article_detail.html
{% extends 'base.html' %} {% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-3 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ article.author }} | {{ article.created_on }}</p>
        <p class="card-text ">{{ object.content | safe }}</p>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

blog/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>Blog test app</title>

    <link
      href="https://fonts.googleapis.com/css?family=Roboto:400,700"
      rel="stylesheet">
    <meta name="google" content="notranslate" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />

  </head>

  <body>
    <style>
      body {
        font-family: "Roboto", sans-serif;
        font-siize: 17px;
        background-color: #fdfdfd;
      }

    .shadow{
           box-shadow: 0 4px 2px -2px rgba(0,0,0,0.1);
       }
      .btn-danger {
        color: #fff;
        background-color: #f00000;
        border-color: #dc281e;
      }

     .masthead {
              background:#3398E1;
              height: auto;
              padding-bottom: 15px;
              box-shadow: 0 16px 48px #E3E7EB;
              padding-top: 10px;
    }

.alert {
  position: relative;
  padding: 0.75rem 1.25rem;
  margin-bottom: 1rem;
  border: 1px solid transparent;
  border-radius: 0.25rem; }

.alert-heading {
  color: inherit; }

.alert-link {
  font-weight: 700; }

.alert-dismissible {
  padding-right: 4rem; }
  .alert-dismissible .close {
    position: absolute;
    top: 0;
    right: 0;
    padding: 0.75rem 1.25rem;
    color: inherit; }

.alert-primary {
  color: #081529;
  background-color: #cfd4dc;
  border-color: #bcc3cd; }
  .alert-primary hr {
    border-top-color: #adb6c2; }
  .alert-primary .alert-link {
    color: black; }

.alert-secondary {
  color: #196953;
  background-color: #d6f4ec;
  border-color: #c5f0e4; }
  .alert-secondary hr {
    border-top-color: #b1ebdb; }
  .alert-secondary .alert-link {
    color: #0f4032; }

.alert-success {
  color: #11694f;
  background-color: #d2f4ea;
  border-color: #c1f0e2; }
  .alert-success hr {
    border-top-color: #acebd8; }
  .alert-success .alert-link {
    color: #0a3d2e; }

.alert-info {
  color: #0c5460;
  background-color: #d1ecf1;
  border-color: #bee5eb; }
  .alert-info hr {
    border-top-color: #abdde5; }
  .alert-info .alert-link {
    color: #062c33; }

.alert-warning {
  color: #856404;
  background-color: #fff3cd;
  border-color: #ffeeba; }
  .alert-warning hr {
    border-top-color: #ffe8a1; }
  .alert-warning .alert-link {
    color: #533f03; }

.alert-danger {
  color: #792424;
  background-color: #fbdada;
  border-color: #f9cbcb; }
  .alert-danger hr {
    border-top-color: #f6b4b4; }
  .alert-danger .alert-link {
    color: #521818; }

.alert-light {
  color: #818182;
  background-color: #fefefe;
  border-color: #fdfdfe; }
  .alert-light hr {
    border-top-color: #ececf6; }
  .alert-light .alert-link {
    color: #686868; }

.alert-dark {
  color: #1b1e21;
  background-color: #d6d8d9;
  border-color: #c6c8ca; }
  .alert-dark hr {
    border-top-color: #b9bbbe; }
  .alert-dark .alert-link {
    color: #040505; }


.fade {
  transition: opacity 0.15s linear; }
  @media screen and (prefers-reduced-motion: reduce) {
    .fade {
      transition: none; } }
  .fade:not(.show) {
    opacity: 0; }

    </style>

    <nav class="navbar navbar-expand-lg navbar-light bg-light shadow" id="mainNav">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}" >Blog test app</a>
        <button
          class="navbar-toggler navbar-toggler-right"
          type="button"
          data-toggle="collapse"
          data-target="#navbarResponsive"
          aria-controls="navbarResponsive"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
                <li class="nav-item {% if 'dashboard' in request.path %}active{% endif %} mr-3">
                    <a class="nav-link" href="{% url 'dashboard' %}">Dashboard</a>
                </li>
                <li class="nav-item mr-3">
                    <a class="nav-link" href="{% url 'logout' %}">
                        <i class="fas fa-sign-out-alt"></i>
                        Logout</a>
                </li>
                {% else %}
                <li class="nav-item {% if 'register' in request.path %}active{% endif %} mr-3">
                    <a class="nav-link" href="{% url 'register' %}">
                        <i class="fas fa-user-plus"></i> Register</a>
                </li>
                <li class="nav-item {% if 'login' in request.path %}active{% endif %} mr-3">
                    <a class="nav-link" href="{% url 'login' %}">
                        <i class="fas fa-sign-in-alt"></i>
                        Login</a>
                </li>

              {% endif %}
            </li>
          </ul>
        </div>
      </div>
    </div>
    </nav>


            {% block content %}
          <!-- Content Goes here -->
            {% endblock content %}

    <!-- Footer -->

  </body>
</html>

blog/templates/index.html
{% extends "base.html" %}

 {% block content %}
<style>

    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text{
    color: white;
  }
    .card{
    box-shadow: 0 16px 48px #E3E7EB;
}
</style>

            <div class="container">
                <div class="row">

              <!-- Blog Entries Column -->
              <div class="col-md-8 mt-3 left">
                    {% for article in article_list %}
                <div class="card mb-4" >
                  <div class="card-body">
                    <h2 class="card-title">{{ article.title }}</h2>
                    <p class="card-text text-muted h6">{{ article.author }} | {{ article.created_on}} </p>

                    <p class="card-text">{{article.content| slice:":200" | safe}}</p>
                    <a href="{% url 'article_detail' article.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                  </div>

                </div>
                {% endfor %}
            </div>
            </div>
        </div>
        {% if is_paginated %}
          <nav aria-label="Page navigation conatiner"></nav>
          <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
          </ul>
          </nav>
        </div>
        {% endif %}
{%endblock%}

blog/templates/new_article.html
{% extends "base.html" %}
{% block content %}
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<!-- include summernote css/js -->
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
<section id="article" class="bg-light py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto">

            <div class="card-body">
              <form method="post" action="{% url 'new_article' %}">

                {% csrf_token %}
                {{ form | safe }}

                <br/>
                <input type="submit" value="Submit" class="btn btn-secondary btn-block">

              </form>
            </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

blog/templates/partials/_alerts.html
{% if messages %}

{% for message in messages %}
<div id="message" class="container">
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            <span class="sr-only">Close</span>
        </button>
        <strong>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            Error
            {% else %}
            {{ message.tags|title }}
            {% endif %}
        </strong> {{ message }}
    </div>
    {% endfor %}
</div>
{% endfor %}

{% endif %}